import { RuntimeEntitySpec, RuntimeEndpointSpec } from './runtime.types';

export const ENTITY_SPECS: RuntimeEntitySpec[] = [
  {
    key: 'lead',
    label: 'Lead',
    table: 'leads',
    permissionSlug: 'leads:manage',
    formKey: 'lead',
    routeBase: '/api/data/lead',
    fields: [
      'title',
      'source',
      'category',
      'stage',
      'accountId',
      'primaryContactId',
      'phone',
      'email',
      'estimatedValue',
      'budgetMin',
      'budgetMax',
      'ownerId',
      'expectedCloseAt',
      'nextFollowUpAt',
      'probability',
      'requirementSummary',
      'lostReason',
      'tags',
    ],
    filters: ['q', 'status', 'source', 'ownerId', 'page', 'limit', 'sortBy', 'sortOrder'],
    sampleCreatePayload: {
      title: 'Interior design for 3BHK',
      source: 'website',
      category: 'residential',
      stage: 'new',
      estimatedValue: 1500000,
      ownerId: 'uuid',
    },
    sampleUpdatePayload: {
      id: 'uuid',
      title: 'Updated lead title',
      stage: 'qualified',
      probability: 65,
    },
    sampleListPayload: {
      page: 1,
      limit: 20,
      q: 'villa',
    },
    sampleActionPayload: {
      id: 'uuid',
      status: 'qualified',
      reason: 'Qualified by sales team',
    },
    lookups: ['lead_source', 'lead_stage', 'lead_category'],
  },
  {
    key: 'contact',
    label: 'Contact',
    table: 'contacts',
    permissionSlug: 'contacts:manage',
    formKey: 'contact',
    routeBase: '/api/data/contact',
    fields: [
      'accountId',
      'firstName',
      'lastName',
      'email',
      'phone',
      'altPhone',
      'designation',
      'category',
      'isPrimary',
      'address',
      'city',
      'state',
      'country',
      'timezone',
    ],
    filters: ['q', 'category', 'accountId', 'page', 'limit', 'sortBy', 'sortOrder'],
    sampleCreatePayload: {
      firstName: 'John',
      lastName: 'Doe',
      email: 'john@example.com',
      category: 'architect',
    },
    sampleUpdatePayload: {
      id: 'uuid',
      designation: 'Principal Architect',
      timezone: 'America/New_York',
    },
    sampleListPayload: { page: 1, limit: 20, q: 'john' },
    lookups: ['contact_category'],
  },
  {
    key: 'account',
    label: 'Account',
    table: 'accounts',
    permissionSlug: 'contacts:manage',
    formKey: 'account',
    routeBase: '/api/data/account',
    fields: ['name', 'type', 'industry', 'website', 'ownerId', 'primaryAddress', 'billingAddress', 'taxId', 'notes'],
    filters: ['q', 'type', 'industry', 'page', 'limit', 'sortBy', 'sortOrder'],
    sampleCreatePayload: {
      name: 'Acme Interiors',
      type: 'company',
      industry: 'real-estate',
    },
    sampleUpdatePayload: {
      id: 'uuid',
      website: 'https://example.com',
      notes: 'High priority client',
    },
    sampleListPayload: { page: 1, limit: 20 },
  },
  {
    key: 'project',
    label: 'Project',
    table: 'projects',
    permissionSlug: 'projects:manage',
    formKey: 'project',
    routeBase: '/api/data/project',
    fields: [
      'leadId',
      'accountId',
      'contactId',
      'title',
      'templateId',
      'projectType',
      'managerId',
      'status',
      'health',
      'budget',
      'startDate',
      'endDate',
      'location',
      'description',
    ],
    filters: ['q', 'status', 'managerId', 'accountId', 'page', 'limit', 'sortBy', 'sortOrder'],
    sampleCreatePayload: {
      title: 'Sector 45 Villa',
      status: 'planning',
      budget: 2500000,
    },
    sampleUpdatePayload: {
      id: 'uuid',
      status: 'active',
      health: 'green',
    },
    sampleListPayload: { page: 1, limit: 20 },
    lookups: ['project_status', 'project_health', 'project_type'],
  },
  {
    key: 'task',
    label: 'Task',
    table: 'tasks',
    permissionSlug: 'tasks:manage',
    formKey: 'task',
    routeBase: '/api/data/task',
    fields: [
      'projectId',
      'phaseId',
      'milestoneId',
      'parentTaskId',
      'title',
      'description',
      'assigneeId',
      'priority',
      'status',
      'plannedStartAt',
      'dueAt',
      'estimatedHours',
      'dependencyIds',
      'watcherIds',
    ],
    filters: ['q', 'status', 'priority', 'projectId', 'assigneeId', 'page', 'limit', 'sortBy', 'sortOrder'],
    sampleCreatePayload: {
      projectId: 'uuid',
      title: 'Site measurement',
      priority: 'high',
      status: 'todo',
    },
    sampleUpdatePayload: {
      id: 'uuid',
      status: 'in_progress',
      assigneeId: 'uuid',
    },
    sampleListPayload: { projectId: 'uuid', page: 1, limit: 20 },
    sampleActionPayload: {
      id: 'uuid',
      status: 'blocked',
      reason: 'Awaiting client approval',
    },
  },
  {
    key: 'communication',
    label: 'Communication',
    table: 'communications',
    permissionSlug: 'communications:manage',
    formKey: 'communication',
    routeBase: '/api/data/communication',
    fields: [
      'entityType',
      'entityId',
      'channel',
      'direction',
      'subject',
      'summary',
      'occurredAt',
      'participantIds',
      'nextActionAt',
    ],
    filters: ['entityType', 'entityId', 'channel', 'page', 'limit', 'sortBy', 'sortOrder'],
    sampleCreatePayload: {
      entityType: 'lead',
      entityId: 'uuid',
      channel: 'call',
      subject: 'Discovery call',
    },
    sampleUpdatePayload: {
      id: 'uuid',
      summary: 'Client requested revised timeline',
    },
    sampleListPayload: { entityType: 'lead', entityId: 'uuid' },
  },
  {
    key: 'document',
    label: 'Document',
    table: 'documents',
    permissionSlug: 'documents:manage',
    formKey: 'document',
    routeBase: '/api/data/document',
    fields: ['entityType', 'entityId', 'category', 'title', 'versionLabel', 'approvalRequired', 'shareMode'],
    filters: ['entityType', 'entityId', 'category', 'status', 'page', 'limit', 'sortBy', 'sortOrder'],
    sampleCreatePayload: {
      entityType: 'project',
      entityId: 'uuid',
      title: 'Contract Copy',
      category: 'contract',
    },
    sampleUpdatePayload: {
      id: 'uuid',
      approvalRequired: true,
      shareMode: 'internal',
    },
    sampleListPayload: { entityType: 'project', entityId: 'uuid' },
  },
  {
    key: 'quotation',
    label: 'Quotation',
    table: 'quotations',
    permissionSlug: 'quotations:manage',
    formKey: 'quotation',
    routeBase: '/api/data/quotation',
    fields: ['leadId', 'projectId', 'accountId', 'contactId', 'currency', 'validUntil', 'taxMode', 'lineItems', 'discount', 'terms'],
    filters: ['q', 'status', 'leadId', 'projectId', 'page', 'limit', 'sortBy', 'sortOrder'],
    sampleCreatePayload: {
      leadId: 'uuid',
      currency: 'INR',
      lineItems: [{ description: 'Service A', quantity: 1, unitPrice: 1000 }],
      discount: 0,
    },
    sampleUpdatePayload: {
      id: 'uuid',
      status: 'sent',
      discount: 10,
    },
    sampleListPayload: { page: 1, limit: 20 },
  },
  {
    key: 'expense',
    label: 'Expense',
    table: 'expenses',
    permissionSlug: 'expenses:manage',
    formKey: 'expense',
    routeBase: '/api/data/expense',
    fields: ['projectId', 'category', 'vendorId', 'amount', 'currency', 'expenseDate', 'description', 'receiptDocumentId'],
    filters: ['projectId', 'category', 'page', 'limit', 'sortBy', 'sortOrder'],
    sampleCreatePayload: {
      projectId: 'uuid',
      category: 'materials',
      amount: 1200,
      currency: 'INR',
    },
    sampleUpdatePayload: {
      id: 'uuid',
      description: 'Updated receipt notes',
    },
    sampleListPayload: { page: 1, limit: 20 },
  },
];

export const ENDPOINT_SPECS: RuntimeEndpointSpec[] = [
  {
    endpointKey: 'meta.bootstrap',
    method: 'GET',
    route: '/api/meta/bootstrap',
    permissionSlug: 'settings:view',
    auth: 'session',
    dispatcherFn: 'fn_metadata_operations',
    requestShape: '{}',
    responseShape: '{ rid, statusCode, data }',
  },
  {
    endpointKey: 'meta.entities',
    method: 'GET',
    route: '/api/meta/entities',
    permissionSlug: 'settings:view',
    auth: 'session',
    dispatcherFn: 'fn_metadata_operations',
    requestShape: '{}',
    responseShape: '{ rid, statusCode, data[] }',
  },
  {
    endpointKey: 'meta.entity',
    method: 'GET',
    route: '/api/meta/entities/:entityKey',
    permissionSlug: 'settings:view',
    auth: 'session',
    dispatcherFn: 'fn_metadata_operations',
    requestShape: '{ entityKey }',
    responseShape: '{ rid, statusCode, data }',
  },
  {
    endpointKey: 'data.list',
    method: 'POST',
    route: '/api/data/:entityKey/list',
    permissionSlug: 'dynamic:view',
    auth: 'session',
    dispatcherFn: 'fn_data_operations',
    requestShape: '{ filters, query, page, limit }',
    responseShape: '{ rid, statusCode, data[], meta }',
  },
  {
    endpointKey: 'data.get',
    method: 'POST',
    route: '/api/data/:entityKey/get',
    permissionSlug: 'dynamic:view',
    auth: 'session',
    dispatcherFn: 'fn_data_operations',
    requestShape: '{ id }',
    responseShape: '{ rid, statusCode, data }',
  },
  {
    endpointKey: 'data.create',
    method: 'POST',
    route: '/api/data/:entityKey/create',
    permissionSlug: 'dynamic:create',
    auth: 'session',
    dispatcherFn: 'fn_data_operations',
    requestShape: '{ ...entityFields }',
    responseShape: '{ rid, statusCode, data }',
  },
  {
    endpointKey: 'data.update',
    method: 'POST',
    route: '/api/data/:entityKey/update',
    permissionSlug: 'dynamic:update',
    auth: 'session',
    dispatcherFn: 'fn_data_operations',
    requestShape: '{ id, ...entityFields }',
    responseShape: '{ rid, statusCode, data }',
  },
  {
    endpointKey: 'data.delete',
    method: 'POST',
    route: '/api/data/:entityKey/delete',
    permissionSlug: 'dynamic:delete',
    auth: 'session',
    dispatcherFn: 'fn_data_operations',
    requestShape: '{ id }',
    responseShape: '{ rid, statusCode, data }',
  },
  {
    endpointKey: 'data.bulk',
    method: 'POST',
    route: '/api/data/:entityKey/bulk',
    permissionSlug: 'dynamic:bulk',
    auth: 'session',
    dispatcherFn: 'fn_data_operations',
    requestShape: '{ ids[], action, payload }',
    responseShape: '{ rid, statusCode, data }',
  },
  {
    endpointKey: 'action.execute',
    method: 'POST',
    route: '/api/action/:actionKey',
    permissionSlug: 'dynamic:action',
    auth: 'session',
    dispatcherFn: 'fn_action_operations',
    requestShape: '{ ...actionPayload }',
    responseShape: '{ rid, statusCode, data }',
  },
  {
    endpointKey: 'contract.frontend',
    method: 'GET',
    route: '/api/contracts/frontend',
    permissionSlug: 'public',
    auth: 'public',
    dispatcherFn: 'fn_contract_operations',
    requestShape: '{}',
    responseShape: '{ rid, statusCode, data }',
  },
];

